version: "3.8"
services:
  traefik:
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.web.http.redirections.entryPoint.to=websecure  
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.web.http.redirections.entrypoint.permanent=true
      - --certificatesresolvers.letsencrypt.acme.email=${LETS_ENCRYPT_EMAIL}
      - --certificatesresolvers.letsencrypt.acme.storage=/acme.json
      - --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web
    ports:
      - 443:443
    volumes:
      - ./traefik/acme.json:/acme.json
  jid-server:
    labels:
      traefik.http.routers.jid-server.tls: true
      traefik.http.routers.jid-server.tls.certresolver: letsencrypt
  jid-ui:
    labels:
      traefik.http.routers.jid-ui.tls: true
      traefik.http.routers.jid-ui.tls.certresolver: letsencrypt
