version: "3.8"
services:
  traefik:
    image: traefik:2.6
    container_name: traefik
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  jid-server:
    image: ghcr.io/jotajoti/jid-server:latest
    container_name: jid-server
    ports:
      - 8081:8080
    environment:
      database: /usr/src/app/data/jiddata.db
    labels:
      traefik.enable: true
      traefik.http.routers.jid-server.rule: Host(`${SERVER_DOMAIN}`) && PathPrefix(`/api`)
    volumes:
      - ./data/:/usr/src/app/data/
  jid-ui:
    image: jotajoti/jid-ui:latest
    ports:
      - 80
    labels:
      traefik.enable: true
      traefik.http.routers.jid-ui.rule: Host(`${SERVER_DOMAIN}`)
    environment:
      - REACT_APP_API_URL=${API_SERVER_URL}
