name: Deploy to Oracle Cloud

on:
  workflow_call

jobs:
  docker-pull:
    name: Docker Pull
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.ORACLE_CLOUD_HOST }}
          username: ${{ secrets.ORACLE_CLOUD_USER }}
          key: ${{ secrets.ORACLE_CLOUD_KEY }}
          port: ${{ secrets.ORACLE_CLOUD_PORT }}
          script: cd workspace && sudo docker compose pull

  docker-up:
    name: Redeploy updated containers
    needs: docker-pull
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.ORACLE_CLOUD_HOST }}
          username: ${{ secrets.ORACLE_CLOUD_USER }}
          key: ${{ secrets.ORACLE_CLOUD_KEY }}
          port: ${{ secrets.ORACLE_CLOUD_PORT }}
          script: cd workspace && sudo docker compose up -d

  wait:
    name: Wait for healthy services
    needs: docker-up
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.ORACLE_CLOUD_HOST }}
          username: ${{ secrets.ORACLE_CLOUD_USER }}
          key: ${{ secrets.ORACLE_CLOUD_KEY }}
          port: ${{ secrets.ORACLE_CLOUD_PORT }}
          script: |
            cd workspace
            until curl --fail --silent localhost:8080/api/http/services/jid-server-workspace@docker | jq -e '.serverStatus | to_entries | all(.value == "UP")' ; do
              echo "Waiting for service to start"
              sleep 2
            done
            echo "Service started"
